# Generated by Django 4.0.6 on 2022-08-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinpages', '0002_balance_remove_income_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name_plural': 'balances'},
        ),
        migrations.AddField(
            model_name='balance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(),
        ),
    ]
